services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: calendarium-backend
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=env
      - PORT=6969
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev
    networks:
      - calendarium-network

networks:
  calendarium-network:
    driver: bridge
